import Script from "next/script";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import dynamic from "next/dynamic";
import { SocketProvider } from "@/components/socket-provider";

const ClientQueryProvider = dynamic(
  () =>
    import("@/components/client-query-provider").then(
      (mod) => mod.ClientQueryProvider
    ),
  { ssr: false }
);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script src="https://telegram.org/js/telegram-web-app.js" />
      <body className={inter.className}>
        <ClientQueryProvider>
          <SocketProvider>
            <main>{children}</main>
          </SocketProvider>
        </ClientQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
